# Topic Modelling

In [4]:
import pandas as pd

In [5]:
npr = pd.read_csv('npr.csv')

In [52]:
npr.shape

(11992, 1)

In [6]:
npr.head()

Article
0  In the Washington of 2016, even when the polic...
1    Donald Trump has used Twitter  —   his prefe...
2    Donald Trump is unabashedly praising Russian...
3  Updated at 2:50 p. m. ET, Russian President Vl...
4  From photography, illustration and video, to d...

In [7]:
npr['Article'][0]

'In the Washington of 2016, even when the policy can be bipartisan, the politics cannot. And in that sense, this year shows little sign of ending on Dec. 31. When President Obama moved to sanction Russia over its alleged interference in the U. S. election just concluded, some Republicans who had long called for similar or more severe measures could scarcely bring themselves to approve. House Speaker Paul Ryan called the Obama measures ”appropriate” but also ”overdue” and ”a prime example of this administration’s ineffective foreign policy that has left America weaker in the eyes of the world.” Other GOP leaders sounded much the same theme. ”[We have] been urging President Obama for years to take strong action to deter Russia’s worldwide aggression, including its   operations,” wrote Rep. Devin Nunes,  . chairman of the House Intelligence Committee. ”Now with just a few weeks left in office, the president has suddenly decided that some stronger measures are indeed warranted.” Appearing 

In [8]:
npr['Article'][4000]

'The headline shocked the   world of the surface Navy: Seven sailors aboard the destroyer USS Fitzgerald were killed, and other crew members injured, when the warship collided with a cargo vessel off Japan. As the Navy family grieves, both it and the wider world are asking the same question: How did this happen? The short answer is that no one knows  —   yet. Official inquiries into what led up to the encounter could take months or more. The Navy and the U. S. Coast Guard both likely will eventually issue reports that describe what happened and could make recommendations for preventing another such accident. ”I will not speculate on how long these investigations will last,” said Vice Adm. Joseph Aucoin, commander of the Navy’s 7th Fleet. The Fitzgerald and the other ships of Destroyer Squadron 15, based outside Tokyo, fall under his authority. There are clues, however, that explain how something like the Fitzgerald’s collision could happen, including photographs of the ships involved, 

In [9]:
from sklearn.feature_extraction.text import CountVectorizer

In [10]:
cv = CountVectorizer(max_df=0.95,min_df=2,stop_words='english')

In [11]:
dtm = cv.fit_transform(npr['Article'])
dtm.shape

(11992, 54777)

In [12]:
from sklearn.decomposition import LatentDirichletAllocation

In [13]:
LDA = LatentDirichletAllocation(n_components=7,random_state=42)

In [14]:
LDA.fit(dtm)

LatentDirichletAllocation(n_components=7, random_state=42)

In [15]:
len(cv.get_feature_names())

C:\Users\DELL PC\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


54777

In [16]:
type(cv.get_feature_names())

list

In [17]:
import random

random_wor_id = random.randint(0,54777)

cv.get_feature_names()[10]

'01'

In [18]:
len(LDA.components_)

7

In [19]:
type(LDA.components_)

numpy.ndarray

In [20]:
LDA.components_.shape

(7, 54777)

In [21]:
LDA.components_

array([[8.64332806e+00, 2.38014333e+03, 1.42900522e-01, ...,
        1.43006821e-01, 1.42902042e-01, 1.42861626e-01],
       [2.76191749e+01, 5.36394437e+02, 1.42857148e-01, ...,
        1.42861973e-01, 1.42857147e-01, 1.42906875e-01],
       [7.22783888e+00, 8.24033986e+02, 1.42857148e-01, ...,
        6.14236247e+00, 2.14061364e+00, 1.42923753e-01],
       ...,
       [3.11488651e+00, 3.50409655e+02, 1.42857147e-01, ...,
        1.42859912e-01, 1.42857146e-01, 1.42866614e-01],
       [4.61486388e+01, 5.14408600e+01, 3.14281373e+00, ...,
        1.43107628e-01, 1.43902481e-01, 2.14271779e+00],
       [4.93991422e-01, 4.18841042e+02, 1.42857151e-01, ...,
        1.42857146e-01, 1.43760101e-01, 1.42866201e-01]])

In [22]:
single_topic = LDA.components_[0]

In [23]:
single_topic.argsort()

array([ 2475, 18302, 35285, ..., 22673, 42561, 42993], dtype=int64)

In [24]:
for i in range(LDA.components_.shape[0]):
    for j in range(LDA.components_.shape[1]):
        print(LDA.components_[i, j])

8.64332805875264
2380.1433268708574
0.14290052184739976
3.142640924081648
0.14285714788271778
0.14374293592160522
0.14300295535120078
0.1428782264862716
0.14310356467476637
0.1429001477760004
7.994767552532631
0.14467518582259228
1.175700091517506
0.1507060844051734
4.290258457966447
1.1422765800764472
0.1432022153913123
1.0350010305839998
0.14321376631285673
0.14651528453781143
1.142733910701622
0.14290535789705258
0.1445884662569824
4.005406400475973
1.1157697307312633
1.5717730041129585
0.142857145493047
2.7555614153323202
0.14436376703407852
1.5737414885242897
0.20902189613189098
0.14337674602461317
1.0066823278167991
0.14314086571836981
1.1714930511393418
10.501417015371443
0.5006418095782974
2.1359566644146417
0.14322929554062105
0.14594528417923655
0.14285716122510395
0.14303910612078605
710.165940507703
432.5386923956621
1.903301814360352
12.951719598394925
0.14354008516916505
1.6284749344246199
9.038010767990233
4.195433528845232
0.6879959272330369
2.1421447279465156
7.5125382

0.14285715514254732
0.14309917348102427
0.1428571570861748
0.14292496026378862
172.02116854367253
34.395575518703026
10.005966781787599
0.14307753064506715
0.22918950196106697
91.83603527546535
0.14334373918168072
0.14285718644891296
0.14285714497666344
0.14391803493745103
0.14296822198025433
0.14294201339155235
0.14321325892938785
0.14560089406848478
0.1428571492367922
0.16284653524946915
0.14313184144303284
0.1428571762370194
0.1429902737342692
0.14285714745562839
0.1431652523599037
0.14324036577242502
4.00420352332174
0.14316315787454395
8.52356775341618
0.1446974285085166
0.14298196663032095
0.14346204112858515
0.14287489555855717
2.795558195784358
3.5180981575656705
0.14407545910572644
3.374097110682162
0.14285715232515442
0.14297643571256385
8.348170058152443
0.14495909011774058
3.206243999740604
15.14239437820602
9.973046882449955
4.119413295855171
0.1429737476068509
0.1428648230213244
0.1428571476030961
0.1432362570521976
0.14287658875026854
0.14285715306192998
0.14295405075671

47.049292389705634
5.142294933545283
7.052327748928967
0.14302651416264117
1.9095894046340398
70.55309505085071
0.1446255765355032
0.1431135565262998
0.14285715103122723
0.14285715683923536
0.1428842248343574
0.14336470680328575
0.14287027566864552
0.14363225636283758
0.14290633154961832
0.14286491721187372
0.14343208538942429
61.699061115867224
9.60944502158527
0.1428571436575392
0.1435931947549262
0.1430019489163539
0.14398445136623203
0.1428571466066475
0.18049533915448265
0.14295249074673813
0.14321813391355648
0.14288574513882252
0.14289428458293288
3.140842078723772
0.1428588084802701
0.1428984578420678
0.14285715487123543
0.14285715590167453
0.14317842114674784
39.87415355318679
0.14285715264091428
1.1431780131856089
0.14344971897053954
0.1430686376120055
6.709689928586458
0.14289841335646425
0.14298966435741362
0.1438317919656713
0.14308097866792113
0.14301517996781407
0.14286129012989768
6.595840063192857
0.14308841172883552
0.1428571459956279
0.14285715118189654
0.78977835057

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



In [25]:
data = pd.DataFrame(LDA.components_)

In [26]:
data.head()

0            1         2         3         4         5         6      \
0   8.643328  2380.143327  0.142901  3.142641  0.142857  0.143743  0.143003   
1  27.619175   536.394437  0.142857  0.142861  0.143092  1.168792  0.142862   
2   7.227839   824.033986  0.142857  0.142928  0.143214  0.142867  0.143010   
3   1.752141   900.736692  0.142857  0.142857  1.768809  2.984565  0.142857   
4   3.114887   350.409655  0.142857  0.142915  0.143387  0.142943  2.316872   

      7         8         9      ...     54767     54768     54769     54770  \
0  0.142878  0.143104  0.142900  ...  0.142857  0.159712  0.143003  0.156732   
1  0.144935  1.896723  0.142862  ...  0.142881  0.143611  0.143911  0.142857   
2  0.142902  0.142857  0.142922  ...  0.143010  0.143709  0.144234  0.142857   
3  1.159362  1.387008  0.142864  ...  0.142883  0.142897  3.712762  0.147033   
4  1.140668  0.144594  0.142869  ...  0.142857  6.928944  0.142926  0.142857   

      54771     54772     54773     54774     54775     54776  
0  0.987469  0.142857  0.142858  0.143007  0.142902  0.142862  
1  0.142967  0.142857  0.142858  0.142862  0.142857  0.142907  
2  2.373677  3.124346  0.142966  6.142362  2.140614  0.142924  
3  4.066328  0.142857  0.142870  0.142944  0.143107  0.142857  
4  0.142872  0.142989  0.142863  0.142860  0.142857  0.142867  

[5 rows x 54777 columns]

In [42]:
data.max(axis=1)

0     6247.245511
1    10102.177169
2    13636.686911
3    12688.532826
4    15728.662700
5     8261.013120
6     6344.397176
dtype: float64

In [43]:
single_topic = LDA.components_[0]
single_topic

array([8.64332806e+00, 2.38014333e+03, 1.42900522e-01, ...,
       1.43006821e-01, 1.42902042e-01, 1.42861626e-01])

In [46]:
single_topic.argsort()[-10:]

array([33390, 36310, 21228, 10425, 31464,  8149, 36283, 22673, 42561,
       42993], dtype=int64)

In [47]:
top_ten_words = single_topic.argsort()[-10:]

In [48]:
top_twenty_words = single_topic.argsort()[-20:]

In [49]:
for index in top_twenty_words:
    print(cv.get_feature_names()[index])

C:\Users\DELL PC\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


president
state
tax
insurance
trump
companies
money
year
federal
000
new
percent
government
company
million
care
people
health
said
says


In [51]:
for i,topic in enumerate(LDA.components_):
    print(f" topic {i}")
    print([cv.get_feature_names()[index] for index in topic.argsort()[-15:]])
    print('\n\n')

 topic 0


C:\Users\DELL PC\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


['companies', 'money', 'year', 'federal', '000', 'new', 'percent', 'government', 'company', 'million', 'care', 'people', 'health', 'said', 'says']



 topic 1
['military', 'house', 'security', 'russia', 'government', 'npr', 'reports', 'says', 'news', 'people', 'told', 'police', 'president', 'trump', 'said']



 topic 2
['way', 'world', 'family', 'home', 'day', 'time', 'water', 'city', 'new', 'years', 'food', 'just', 'people', 'like', 'says']



 topic 3
['time', 'new', 'don', 'years', 'medical', 'disease', 'patients', 'just', 'children', 'study', 'like', 'women', 'health', 'people', 'says']



 topic 4
['voters', 'vote', 'election', 'party', 'new', 'obama', 'court', 'republican', 'campaign', 'people', 'state', 'president', 'clinton', 'said', 'trump']



 topic 5
['years', 'going', 've', 'life', 'don', 'new', 'way', 'music', 'really', 'time', 'know', 'think', 'people', 'just', 'like']



 topic 6
['student', 'years', 'data', 'science', 'university', 'people', 'time', 'schools', 'just', 

In [54]:
topic_results = LDA.transform(dtm)

In [56]:
topic_results.shape

(11992, 7)

In [57]:
topic_results[0]

array([1.61040465e-02, 6.83341493e-01, 2.25376318e-04, 2.25369288e-04,
       2.99652737e-01, 2.25479379e-04, 2.25497980e-04])

In [58]:
topic_results[0].round(2)

array([0.02, 0.68, 0.  , 0.  , 0.3 , 0.  , 0.  ])

In [62]:
topic_results[0].argmax()

1

In [63]:
npr['Topic'] = topic_results.argmax(axis=1)

In [64]:
npr

Article  Topic
0      In the Washington of 2016, even when the polic...      1
1        Donald Trump has used Twitter  —   his prefe...      1
2        Donald Trump is unabashedly praising Russian...      1
3      Updated at 2:50 p. m. ET, Russian President Vl...      1
4      From photography, illustration and video, to d...      2
...                                                  ...    ...
11987  The number of law enforcement officers shot an...      1
11988    Trump is busy these days with victory tours,...      4
11989  It’s always interesting for the Goats and Soda...      3
11990  The election of Donald Trump was a surprise to...      4
11991  Voters in the English city of Sunderland did s...      0

[11992 rows x 2 columns]

# Non-negative Matrix Factorization

In [1]:
import pandas as pd
npr = pd.read_csv('npr.csv')

In [2]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [4]:
tfidf = TfidfVectorizer(max_df=0.95, min_df=2, stop_words='english')

In [5]:
dtm = tfidf.fit_transform(npr['Article'])

In [6]:
dtm

<11992x54777 sparse matrix of type '<class 'numpy.float64'>'
	with 3033388 stored elements in Compressed Sparse Row format>

In [7]:
from sklearn.decomposition import NMF

In [8]:
nmf_model = NMF(n_components=7, random_state = 42)

In [9]:
nmf_model.fit(dtm)

NMF(n_components=7, random_state=42)

In [11]:
nmf_model.components_.shape

(7, 54777)

In [35]:
for index,topic in enumerate(nmf_model.components_):
    print(f'Topic {index}')
    print([tfidf.get_feature_names()[i] for i in topic.argsort()[-15:]])
    print('\n')

Topic 0
['new', 'research', 'like', 'patients', 'health', 'disease', 'percent', 'women', 'virus', 'study', 'water', 'food', 'people', 'zika', 'says']


Topic 1
['gop', 'pence', 'presidential', 'russia', 'administration', 'election', 'republican', 'obama', 'white', 'house', 'donald', 'campaign', 'said', 'president', 'trump']


Topic 2
['senate', 'house', 'people', 'act', 'law', 'tax', 'plan', 'republicans', 'affordable', 'obamacare', 'coverage', 'medicaid', 'insurance', 'care', 'health']


Topic 3
['officers', 'syria', 'security', 'department', 'law', 'isis', 'russia', 'government', 'state', 'attack', 'president', 'reports', 'court', 'said', 'police']


Topic 4
['primary', 'cruz', 'election', 'democrats', 'percent', 'party', 'delegates', 'vote', 'state', 'democratic', 'hillary', 'campaign', 'voters', 'sanders', 'clinton']


Topic 5
['love', 've', 'don', 'album', 'way', 'time', 'song', 'life', 'really', 'know', 'people', 'think', 'just', 'music', 'like']


Topic 6
['teacher', 'state', 'h

In [40]:
topic_results = nmf_model.transform(dtm)

In [41]:
topic_results.shape

(11992, 7)

In [46]:
topic_results.argmax(axis=1)

array([1, 1, 1, ..., 0, 4, 3], dtype=int64)

In [53]:
pd.DataFrame(topic_results)

0         1         2         3         4         5         6
0      0.000000  0.120797  0.001399  0.059152  0.015192  0.000000  0.000000
1      0.005980  0.126359  0.000000  0.023704  0.000000  0.000000  0.000000
2      0.000000  0.141521  0.000000  0.041432  0.022660  0.000000  0.000000
3      0.000000  0.053003  0.000000  0.062772  0.000000  0.000000  0.000000
4      0.023255  0.015272  0.005685  0.051339  0.009124  0.035379  0.056358
...         ...       ...       ...       ...       ...       ...       ...
11987  0.003014  0.000000  0.004749  0.089878  0.000000  0.000000  0.000171
11988  0.000493  0.076849  0.000000  0.016895  0.015486  0.033580  0.000848
11989  0.031711  0.000000  0.008408  0.018462  0.003731  0.024365  0.000000
11990  0.000000  0.037978  0.010694  0.000456  0.126724  0.011758  0.001003
11991  0.021631  0.006458  0.000710  0.022574  0.012401  0.012793  0.001544

[11992 rows x 7 columns]

In [56]:
npr['Topic'] = topic_results.argmax(axis=1)

In [57]:
npr

Article  Topic
0      In the Washington of 2016, even when the polic...      1
1        Donald Trump has used Twitter  —   his prefe...      1
2        Donald Trump is unabashedly praising Russian...      1
3      Updated at 2:50 p. m. ET, Russian President Vl...      3
4      From photography, illustration and video, to d...      6
...                                                  ...    ...
11987  The number of law enforcement officers shot an...      3
11988    Trump is busy these days with victory tours,...      1
11989  It’s always interesting for the Goats and Soda...      0
11990  The election of Donald Trump was a surprise to...      4
11991  Voters in the English city of Sunderland did s...      3

[11992 rows x 2 columns]

In [58]:
mytopic_dict = {0:'health',1:'election',2:'legis',3:'poli',4:'election',5:'music',6:'edu'}

In [59]:
npr['Topic_Label'] = npr['Topic'].map(mytopic_dict)

In [60]:
npr

Article  Topic Topic_Label
0      In the Washington of 2016, even when the polic...      1    election
1        Donald Trump has used Twitter  —   his prefe...      1    election
2        Donald Trump is unabashedly praising Russian...      1    election
3      Updated at 2:50 p. m. ET, Russian President Vl...      3        poli
4      From photography, illustration and video, to d...      6         edu
...                                                  ...    ...         ...
11987  The number of law enforcement officers shot an...      3        poli
11988    Trump is busy these days with victory tours,...      1    election
11989  It’s always interesting for the Goats and Soda...      0      health
11990  The election of Donald Trump was a surprise to...      4    election
11991  Voters in the English city of Sunderland did s...      3        poli

[11992 rows x 3 columns]